# Generated by Django 4.0.5 on 2022-06-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Номер заказа')),
                ('usd_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Стоимость, $')),
                ('rur_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Стоимость, руб')),
                ('delivery_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлен')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'db_table': 'orders',
            },
        ),
    ]
