# Generated by Django 4.0.5 on 2022-06-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.BigIntegerField(verbose_name='Номер заказа')),
                ('usd_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Стоимость, $')),
                ('rur_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Стоимость, руб')),
                ('delivery_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
